In [2]:
!pip install numpy
import numpy as np


Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np 

In [6]:
print(np.__version__)


2.1.3


In [7]:
list1 = [1,23,3]
print(list1)


[1, 23, 3]


In [9]:
arr_list1 = np.array(list1)
print(arr_list1)


[ 1 23  3]


In [10]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [13]:
list1 = [1,23,45]  # ye 2 dimension aray hai 
list2 = [3,4,5]
arr_list_2 = np.array([list1,list2])
print(arr_list_2)

[[ 1 23 45]
 [ 3  4  5]]


In [14]:
print(arr_list_2.ndim)

2


In [16]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list_3= np.array([list1, list2, list3])
print(arr_list_3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [17]:
print(arr_list_3.ndim)  # dimensions 



2


In [ ]:
#numpy array attributes 


In [21]:
arr1 = np.array([[1,2,3], [4,5,6]]) # 2 barr square bracket aayengi kyuki 2 dimension array hai
print(arr1)
print("Shape", arr1.shape)
print("Size", arr1.size)
print("dtype", arr1.dtype)
print("n_dim" , arr1.ndim)

[[1 2 3]
 [4 5 6]]
Shape (2, 3)
Size 6
dtype int64
n_dim 2


In [23]:
arr3 = np.array([[1,2,3] ,[4,5,6] , [7,7,8]])
print(arr3.ndim)

2


In [24]:
#array intialization


In [28]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
ones_arr = np.ones((2,5))
print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
#Full aray 

In [33]:
full_arr = np.full((2,3), 8)
# pehle vale to shape aur dusre vale konsa bharna hai 

print(full_arr)

[[8 8 8]
 [8 8 8]]


In [34]:
# identiy matrix sare elements zero honge excel diagnal vale vo one honge sirf 

In [35]:
id_arr = np.eye(3,3)  # it is always square matrix 
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# empty array
print(np.empty(2))



[ 1.02116415e+42 -4.00619054e+15]


In [42]:
# evenly spaced array 
print(np.arange(1,20,3))


[ 1  4  7 10 13 16 19]


In [46]:
#specific value between a range(np.linespace
print(np.linspace(1,20,5))

[ 1.    5.75 10.5  15.25 20.  ]


In [48]:
# random values array but they are in float values 

r_array = np.random.rand(3,2)
print(r_array)

[[0.29866235 0.63198513]
 [0.44631438 0.20573565]
 [0.50264509 0.02612248]]


In [50]:
# random values array but they are i in int 
r_array1 = np.random.randint(1,120 ,(2,3))
print(r_array1)

[[ 8  5  2]
 [10  7 10]]


In [51]:
# array indexing and slicing 


In [55]:
a = np.array([12,3,4,5,6])
print(a)

[12  3  4  5  6]


In [60]:
print(a[-1])

6


In [62]:
# Slicing
# array[start:stop:stop]
a = np.array([1,2,3,4,5])
# stop - index, that is not inculed in output 
print(a)


[1 2 3 4 5]


In [66]:
print(a[0:2]) # first 3 elements 

[1 2]


In [72]:
print(a[-3: ]) # last 3 elements ye slicing se hai 

[3 4 5]


In [75]:
print(a[1:4]) # middle 3 elements

[2 3 4]


In [76]:
print(a[0::2])

[1 3 5]


In [77]:
# indexing and slicing for\
# 2 dimensional


In [78]:
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [86]:
print(arr2[1][0])

4


In [87]:
print(arr1[1:])

[[4 5 6]]


In [92]:
print(arr1[1: ])

[[4 5 6]]


In [94]:
print(arr1[: ,0])
2D: [ rows , collums]
3d : [ layers/height,rows,columms]


[1 4]


In [95]:
arr3 = np.array([[1,2,3], [4,5,6] ,[6,7,8]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [99]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[6 7 8]


In [104]:
print(arr3[0][1])
print(arr3[2][2])


2
8


In [106]:
print(arr3[:, 2]) # 2nd collum value 

[3 6 8]


In [110]:
print(arr3[: , 2 ])
# 1st col value 


[3 6 8]


In [111]:
print(arr3[::2 , 0])  #jump karega 2 value 

[1 6]


In [113]:
print(arr3[::, 1:2]) #slicing on colllums
print(arr3[2:: , 1:2]) #slicing on rows and colums 

[[2]
 [5]
 [7]]
[[7]]


In [114]:
# Array Reshaping and Flattening 

In [118]:
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5 6]


In [122]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)





[[1 2 3]
 [4 5 6]]


In [132]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [133]:
# Array Stacking(vertical,horizontal) and Spliiitng

In [135]:
a= np.array([1,2,3])
b= np.array([4,5,6])

print(np.vstack((a,b))) #vertical stacking row wise 
print("Array Stacking")

print(np.hstack((a,b))) #horizontal stackimg - collum wise 



[[1 2 3]
 [4 5 6]]
Array Stacking
[1 2 3 4 5 6]


In [138]:
c= np.array([(1,2,3), (4,5,6)])
print(np.hsplit(c,3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [140]:
print(np.vsplit(c,2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [141]:
# Mathematical Operations on Array

In [144]:
a = np.array([10,20,30,-40])
print(a)

[ 10  20  30 -40]


In [146]:
print(a+10)
print(a-10)
print(a*10)
print(a/100)

[ 20  30  40 -30]
[  0  10  20 -50]
[ 100  200  300 -400]
[ 0.1  0.2  0.3 -0.4]


In [148]:
b = np.array([1,4,9])
print(b)
print(np.square(b))
print(np.sqrt(b))

[1 4 9]
[ 1 16 81]
[1. 2. 3.]


In [150]:
print(np.sin(b))
print(np.tan(b))
print(np.cos(b))

[ 0.84147098 -0.7568025   0.41211849]
[ 1.55740772  1.15782128 -0.45231566]
[ 0.54030231 -0.65364362 -0.91113026]


In [151]:
# on multiple arrays 

In [156]:
a= np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a,b))

[5 7 9]


In [158]:
print(np.subtract(b,a))

[3 3 3]


In [160]:
print(np.multiply(a,b))
print(np.divide(a,b))


[ 4 10 18]
[0.25 0.4  0.5 ]


In [162]:
print(np.dot(a,b)) #sab mulitply hoke sum

32


In [164]:
a= np.array([(1,2,3), (4,5,6)])
print(a)
print(a.T)   #transpose

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [165]:
# Statistical Function

In [167]:
 a= np.array([[1,2,3] , [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [168]:
print(np.sum(a))

21


In [169]:
print(np.median(a))

3.5


In [171]:
print(np.mean(a))

3.5


In [172]:
print(np.std(a))

1.707825127659933


In [173]:
print(np.min(a))

1


In [175]:
print(np.max(a))

6


In [176]:
# Array Comparison

In [180]:
a= np.array([1,5,3])
b= np.array([4,5,6])
print(a)
print(b)


[1 5 3]
[4 5 6]


In [181]:
print(a==b)
print(np.array_equal(a,b))


[False  True False]
False


In [182]:
# Broadcasting lower dimension ka koi bhi array to higher vake kai sath match karne ki kosish karega bina kisi nokjhok k ye ek commnese vali baat hoti hai 

In [184]:
a= np.array([1,2,3,4])
b = np.array([7])
print(a*b)

[ 7 14 21 28]


In [185]:
#Handling with null values and infinite values 

In [187]:
data1 = np.array([1,2 ,np.nan, 4, np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [188]:
print(np.isnan(data1))

[False False  True False False]


In [189]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [190]:
#save and load array

In [191]:
arr = np.array([1,2,34,55,90])
print(arr)
np.save('my array.npy' ,arr)

[ 1  2 34 55 90]


In [192]:
loadded_arr = np.load('my array.npy')

In [193]:
print(loadded_arr)



[ 1  2 34 55 90]
